## ML3_Validation

### Model quality estimation

## 1. Ответьте на вопросы из введения

## 1.a.  Метод «исключения одного элемента» (Leave-One-Out Cross-Validation — LOOCV)

### Суть работы
Это экстремальный вариант **K-Fold кросс-валидации**, где количество фолдов $K$ равняется общему количеству объектов ($N$) в наборе данных. Модель обучается $N$ раз на $N-1$ объектах, используя оставленный объект для теста.

### Сильные стороны
* **Максимальное использование данных:** Модель обучается почти на 100% выборки, обеспечивая несмещенную оценку.
* **Отсутствие случайности:** Результат LOOCV всегда одинаков при фиксированных гиперпараметрах.

### Ограничения
* **Огромные вычислительные затраты:** Требует $N$ обучений, что невозможно для больших данных и тяжелых алгоритмов.
* **Высокая дисперсия (Variance) оценки:** Сильная корреляция между обучающими выборками может приводить к нестабильным оценкам на новых данных.

## 1.b. Алгоритмы поиска гиперпараметров

В машинном обучении критически важно подобрать оптимальные внешние настройки модели. Существует три основных подхода к автоматизации этого процесса:

### Grid Search (Поиск по сетке)
* **Принцип работы:** Вы вручную задаете точный список значений для каждого параметра. Алгоритм строит координатную сетку из всех возможных пересечений этих значений и последовательно тестирует каждую комбинацию.
* **Недостаток:** «Бездумный» перебор. Он не учится на ошибках и тратит много времени на проверку заведомо плохих веток.

### Random Search (Случайный поиск)
* **Принцип работы:** Вместо тестирования всех точек подряд алгоритм случайным образом выбирает комбинации из заданного диапазона или распределения.
* **Преимущество:** Не дублирует проверки по неважным параметрам. За то же количество шагов тестирует гораздо больше уникальных значений важных признаков, что математически повышает шанс найти оптимум.

### Bayesian Optimization (Байесовская оптимизация)
* **Принцип работы:** «Умный» поиск на основе теории вероятностей. Алгоритм строит внутреннюю суррогатную модель, которая предсказывает качество на основе прошлых попыток.
* **Преимущество:** На каждом шаге оценивает баланс между улучшением параметров в уже известной «хорошей» зоне (*Exploitation*) и исследованием абсолютно новых областей (*Exploration*). Экономит до 90% времени по сравнению с Grid Search.

## 1.c. Классификация методов отбора признаков (Feature Selection) в обучении с учителям

Отбор признаков помогает упростить модель, ускорить её обучение и предотвратить переобучение (overfitting). Все подходы делятся на три большие группы:

### 1. Фильтрующие методы (Filter Methods)
* **Принцип работы:** Оценивают каждый признак отдельно от модели машинного обучения с помощью чистой математической статистики.
* **Плюсы:** Работают молниеносно на терабайтах данных.
* **Минусы:** Рассматривают признаки изолированно. Они не способны заметить ситуации, когда два признака бесполезны по отдельности, но дают идеальный результат при совместном использовании.
* **Примеры:** Корреляция Пирсона, критерий Хи-квадрат ($\chi^2$), взаимная информация (Mutual Information).

### 2. Оберточные методы (Wrapper Methods)
* **Принцип работы:** Используют саму модель машинного обучения как «черный ящик». Специальный внешний алгоритм поочередно добавляет или удаляет признаки из набора и каждый раз заново обучает модель, отслеживая метрику качества.
* **Плюсы:** Учитывают взаимное влияние признаков и особенности конкретной модели.
* **Минусы:** Работают крайне медленно. Требуют сотен или тысяч циклов переобучения модели.
* **Примеры:** Пошаговое добавление (Forward Selection), последовательное удаление (Backward Elimination), рекурсивный отбор признаков (RFE).

### 3. Встроенные методы (Embedded Methods)
* **Принцип работы:** Отбор признаков происходит автоматически прямо в процессе обучения модели благодаря её внутренней математической архитектуре.
* **Плюсы:** Идеальный баланс между скоростью фильтров и точностью оберточных методов.
* **Минусы:** Сильно привязаны к конкретному типу моделей.
* **Примеры:** Штрафные санкции L1-регуляризации в Lasso-регрессии (зануляет веса слабых признаков), анализ важности признаков (Feature Importances) в случайных лесах и бустингах.

## 1.c. Статистические фильтры: Коэффициент Пирсона и Критерий Хи-квадрат ($\chi^2$)

Эти методы оценивают значимость каждого признака изолированно от модели, используя чистую математическую статистику. На основе вашей схемы они относятся к категории **Supervised -> Filters**.

### 1. Коэффициент корреляции Пирсона ($r$)
* **Тип данных:** Применяется только для **непрерывных числовых** признаков (например, рост, вес, температура, цена).
* **Что измеряет:** Силу и направление **линейной** взаимосвязи между признаком $X$ и целевой переменной $Y$.

$$r = \frac{\sum (X_i - \bar{X})(Y_i - \bar{Y})}{\sqrt{\sum (X_i - \bar{X})^2 \sum (Y_i - \bar{Y})^2}}$$

* **Интерпретация результатов:**
  * $r = 1$: Идеальная прямая линейная связь (один растет, второй растет).
  * $r = -1$: Идеальная обратная линейная связь (один растет, второй падает).
  * $r \approx 0$: Линейной связи между признаками **нет**. Такой признак можно смело отфильтровывать и удалять из модели.

### 2. Критерий Хи-квадрат ($\chi^2$)
* **Тип данных:** Применяется для **категориальных (номинальных)** признаков (например, цвет машины, пол, профессия, наличие симптома).
* **Что измеряет:** Степень независимости двух категориальных величин (признака и таргета).

$$\chi^2 = \sum \frac{(O_i - E_i)^2}{E_i}$$

*Где $O_i$ — фактически наблюдаемые частоты в данных (Observed), а $E_i$ — теоретически ожидаемые частоты при условии, что признаки абсолютно независимы (Expected).*

* **Интерпретация результатов:**
  * Алгоритм проверяет нулевую гипотезу: *«Признак и целевая переменная независимы друг от друга»*.
  * Если значение $\chi^2$ очень маленькое (а значение $p\text{-value} > 0.05$), значит, связь между признаком и таргетом чисто случайная. Данный признак отфильтровывается как бесполезный.

## 1.c. Встроенные методы: Lasso-регрессия (L1-регуляризация)

Согласно вашей схеме, этот подход относится к категории **Supervised -> Embedded**. Отбор признаков происходит автоматически прямо в процессе обучения модели за счет ее математической архитектуры.

### Суть работы метода
**Lasso (Least Absolute Shrinkage and Selection Operator)** — это линейная регрессия, к функции потерь которой добавляется «штраф» за сложность. Математика штрафа устроена так, что она прибавляет к ошибке прогнозирования (MSE) сумму абсолютных значений (модулей) всех весов (коэффициентов) модели.

### Математическая формула

$$\text{Ошибка} = \text{MSE} + \alpha \sum_{i=1}^{d} |w_{i}|$$

Где:
* $\text{MSE}$ — среднеквадратичная ошибка модели (качество аппроксимации данных).
* $w_i$ — веса (коэффициенты) перед признаками.
* $\alpha$ (альфа) — гиперпараметр регуляризации. Чем он больше, тем сильнее штраф и тем больше признаков будет исключено.

### Почему веса зануляются строго до нуля? (Геометрия L1)
В процессе обучения алгоритм оптимизации пытается минимизировать эту комбинированную ошибку. 

Ограничение, накладываемое L1-регуляризацией $\sum |w_i| \le C$, геометрически представляет собой **остроугольный ромб** (в многомерном пространстве — кросс-политоп). 
Линии уровня ошибки MSE (овалы) при расширении в первую очередь соприкасаются именно с **вершинами (углами)** этого ромба. На вершинах ромба одна или несколько координат (весов $w_i$) **строго равны нулю**.

* **Итог:** Слабые, зашумленные или дублирующие признаки получают коэффициент `0.0` и полностью выбывают из модели. Так происходит встроенный автоматический отбор признаков.

## Гибридные методы: Permutation Importance и SHAP

Методы **Permutation Importance** и **SHAP** не вписываются в строгую классическую схему «Фильтры vs Обертки». Они находятся ровно посередине, объединяя лучшие качества обоих подходов, из-за чего они крайне рекомендованы к использованию в реальных проектах.

### Почему они занимают промежуточное положение?

* **Как фильтры (Filters):** Они работают молниеносно по сравнению с классическими обертками, потому что нам **НЕ нужно переобучать модель тысячи раз**. Мы обучаем модель всего один раз, а затем анализируем её структуру.
* **Как оберточные методы (Wrappers):** Они не являются абстрактной изолированной статистикой. Они напрямую используют обученную модель машинного обучения как «судью», учитывая сложные нелинейные взаимосвязи и синергию признаков внутри алгоритма.

## 1.c. Значимость перестановок (Permutation Feature Importance)

Это простой, интуитивно понятный и мощный способ оценить важность признаков для **уже обученной** модели машинного обучения (пост-хок анализ).

### Пошаговый алгоритм работы
1. **Фиксация базы:** Берется валидационная (или тестовая) выборка и замеряется исходное качество модели (например, $Accuracy = 0.85$).
2. **Разрушение информации:** Выбирается один конкретный признак (например, *«Возраст»*) и его значения случайным образом перемешиваются (переставляются местами) между строками датасета. Связь этого признака с таргетом полностью уничтожается, но общее распределение признака и структура таблицы не меняются.
3. **Проверка модели:** Модель заставляют сделать предсказания на этом частично «испорченном» датасете и замеряют новое качество.
4. **Оценка важности:** Процесс повторяется по очереди для каждого признака.

### Интерпретация результатов
* Если качество **сильно упало** (например, с $0.85$ до $0.52$) — признак был **критически важным**. Без него модель ломается.
* Если качество **почти не изменилось** (или даже немного выросло) — признак **бесполезен** или дублирует другие данные. Модель его игнорирует.

### Главные плюсы метода
* **Model-Agnostic (Универсальность):** Работает абсолютно с любой моделью (от линейной регрессии до сложных нейросетей), так как оценивает модель как «черный ящик».
* **Защита от переобучения:** В отличие от встроенных `feature_importances_` в деревьях решений (которые часто завышают важность шумных, но непрерывных признаков на обучающей выборке), Permutation Importance считается на **валидационных данных**, что дает честную оценку.

## 1.c. Метод SHAP (Shapley Additive exPlanations)

**SHAP** — это передовой метод объяснения предсказаний («объяснительный ИИ»), основанный на математической теории кооперативных игр Ллойда Шепли (Нобелевская премия по экономике).

* **Принцип работы:** Представьте, что модель предсказала цену квартиры в 10 млн рублей при среднем рынке в 6 млн. SHAP рассматривает признаки квартиры (метро, ремонт, этаж) как игроков одной команды. Он математически перебирает все возможные комбинации (коалиции) этих признаков и вычисляет **чистый вклад каждого фактора** в финальное отклонение (+4 млн).
* **Главный плюс:** Дает как общую картину важности (*Глобальная интерпретируемость*), так и персональный расклад для каждого конкретного клиента или объекта (*Локальная интерпретируемость*).

## 2. Введение — выполните всю предварительную обработку, описанную в предыдущем уроке.

In [1]:
import pandas as pd
import numpy as np
import re
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.model_selection import (
    GroupKFold,
    KFold,
    StratifiedKFold,
    TimeSeriesSplit,
)
import matplotlib.pyplot as plt
import shap
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.inspection import permutation_importance
from sklearn.linear_model import ElasticNet
from sklearn.pipeline import Pipeline
from sklearn.inspection import permutation_importance
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
import optuna
from sklearn.model_selection import cross_val_score
import warnings

In [2]:
warnings.filterwarnings('ignore', category=UserWarning)
warnings.filterwarnings('ignore', message=".*Gradient.*")

In [3]:
train_df = pd.read_json('data/train.json')
train_df.head(5)

,bathrooms,bedrooms,building_id,created,description,display_address,features,latitude,listing_id,longitude,manager_id,photos,price,street_address,interest_level
4,1.0,1,8579a0b0d54db803821a35a4a615e97a,2016-06-16 05:55:27,Spacious 1 Bedroom 1 Bathroom in Williamsburg!...,145 Borinquen Place,"[Dining Room, Pre-War, Laundry in Building, Di...",40.7108,7170325,-73.9539,a10db4590843d78c784171a107bdacb4,[https://photos.renthop.com/2/7170325_3bb5ac84...,2400,145 Borinquen Place,medium
6,1.0,2,b8e75fc949a6cd8225b455648a951712,2016-06-01 05:44:33,BRAND NEW GUT RENOVATED TRUE 2 BEDROOMFind you...,East 44th,"[Doorman, Elevator, Laundry in Building, Dishw...",40.7513,7092344,-73.9722,955db33477af4f40004820b4aed804a0,[https://photos.renthop.com/2/7092344_7663c19a...,3800,230 East 44th,low
9,1.0,2,cd759a988b8f23924b5a2058d5ab2b49,2016-06-14 15:19:59,**FLEX 2 BEDROOM WITH FULL PRESSURIZED WALL**L...,East 56th Street,"[Doorman, Elevator, Laundry in Building, Laund...",40.7575,7158677,-73.9625,c8b10a317b766204f08e613cef4ce7a0,[https://photos.renthop.com/2/7158677_c897a134...,3495,405 East 56th Street,medium
10,1.5,3,53a5b119ba8f7b61d4e010512e0dfc85,2016-06-24 07:54:24,A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...,Metropolitan Avenue,[],40.7145,7211212,-73.9425,5ba989232d0489da1b5f2c45f6688adc,[https://photos.renthop.com/2/7211212_1ed4542e...,3000,792 Metropolitan Avenue,medium
15,1.0,0,bfb9405149bfff42a92980b594c28234,2016-06-28 03:50:23,Over-sized Studio w abundant closets. Availabl...,East 34th Street,"[Doorman, Elevator, Fitness Center, Laundry in...",40.7439,7225292,-73.9743,2c3b41f588fbb5234d8a1e885a436cfa,[https://photos.renthop.com/2/7225292_901f1984...,2795,340 East 34th Street,low

In [4]:
test_df = pd.read_json('data/test.json')
test_df.head(5)

,bathrooms,bedrooms,building_id,created,description,display_address,features,latitude,listing_id,longitude,manager_id,photos,price,street_address
0,1.0,1,79780be1514f645d7e6be99a3de696c5,2016-06-11 05:29:41,Large with awesome terrace--accessible via bed...,Suffolk Street,"[Elevator, Laundry in Building, Laundry in Uni...",40.7185,7142618,-73.9865,b1b1852c416d78d7765d746cb1b8921f,[https://photos.renthop.com/2/7142618_1c45a2c8...,2950,99 Suffolk Street
1,1.0,2,0,2016-06-24 06:36:34,Prime Soho - between Bleecker and Houston - Ne...,Thompson Street,"[Pre-War, Dogs Allowed, Cats Allowed]",40.7278,7210040,-74.0000,d0b5648017832b2427eeb9956d966a14,[https://photos.renthop.com/2/7210040_d824cc71...,2850,176 Thompson Street
2,1.0,0,0,2016-06-17 01:23:39,Spacious studio in Prime Location. Cleanbuildi...,Sullivan Street,"[Pre-War, Dogs Allowed, Cats Allowed]",40.7260,7174566,-74.0026,e6472c7237327dd3903b3d6f6a94515a,[https://photos.renthop.com/2/7174566_ba3a35c5...,2295,115 Sullivan Street
3,1.0,2,f9c826104b91d868e69bd25746448c0c,2016-06-21 05:06:02,For immediate access call Bryan.<br /><br />Bo...,Jones Street,"[Hardwood Floors, Dogs Allowed, Cats Allowed]",40.7321,7191391,-74.0028,41735645e0f8f13993c42894023f8e58,[https://photos.renthop.com/2/7191391_8c2f2d49...,2900,23 Jones Street
5,1.0,1,81062936e12ee5fa6cd2b965698e17d5,2016-06-16 07:24:27,Beautiful TRUE 1 bedroom in a luxury building ...,Exchange Place,"[Roof Deck, Doorman, Elevator, Fitness Center,...",40.7054,7171695,-74.0095,a742cf7dd3b2627d83417bc3a1b3ec96,[https://photos.renthop.com/2/7171695_089ffee2...,3254,20 Exchange Place

In [5]:
def clean_feature_list(feat_list):
    cleaned = []
    for item in feat_list:
    
        clean_item = re.sub(r"[\[\]'\"\s]", "", str(item))
        cleaned.append(clean_item)
    return cleaned

train_df['features_cleaned'] = train_df['features'].apply(clean_feature_list)

huge_list = []
for index, row in train_df.iterrows():
    huge_list.extend(row['features_cleaned'])

unique_values_count = len(set(huge_list))
print(f"Количество уникальных значений в списке удобств: {unique_values_count}")

cnt = Counter(huge_list)
print("\nПроверка соответствия скриншоту чек-листа (most_common(21)):")
print(cnt.most_common(21))

Количество уникальных значений в списке удобств: 1545

Проверка соответствия скриншоту чек-листа (most_common(21)):
[('Elevator', 25915), ('CatsAllowed', 23540), ('HardwoodFloors', 23527), ('DogsAllowed', 22035), ('Doorman', 20898), ('Dishwasher', 20426), ('NoFee', 18062), ('LaundryinBuilding', 16344), ('FitnessCenter', 13252), ('Pre-War', 9148), ('LaundryinUnit', 8738), ('RoofDeck', 6542), ('OutdoorSpace', 5268), ('DiningRoom', 5136), ('HighSpeedInternet', 4299), ('Balcony', 2992), ('SwimmingPool', 2730), ('LaundryInBuilding', 2593), ('NewConstruction', 2559), ('Terrace', 2283), ('Exclusive', 2167)]

In [6]:
top_20_features = [
    'Elevator', 'CatsAllowed', 'HardwoodFloors', 'DogsAllowed', 'Doorman', 
    'Dishwasher', 'NoFee', 'LaundryinBuilding', 'FitnessCenter', 'Pre-War', 
    'LaundryinUnit', 'RoofDeck', 'OutdoorSpace', 'DiningRoom', 'HighSpeedInternet', 
    'Balcony', 'SwimmingPool', 'LaundryInBuilding', 'NewConstruction', 'Terrace'
]

for feat in top_20_features:
   
    train_df[feat] = train_df['features_cleaned'].apply(lambda x: 1 if feat in x else 0)

feature_list = ['bathrooms', 'bedrooms'] + top_20_features

print(f"Создано новых признаков: {len(top_20_features)}")
print(f"Общее количество признаков в переменной feature_list: {len(feature_list)}")
print("Список всех 22 признаков для обучения:", feature_list)

Создано новых признаков: 20
Общее количество признаков в переменной feature_list: 22
Список всех 22 признаков для обучения: ['bathrooms', 'bedrooms', 'Elevator', 'CatsAllowed', 'HardwoodFloors', 'DogsAllowed', 'Doorman', 'Dishwasher', 'NoFee', 'LaundryinBuilding', 'FitnessCenter', 'Pre-War', 'LaundryinUnit', 'RoofDeck', 'OutdoorSpace', 'DiningRoom', 'HighSpeedInternet', 'Balcony', 'SwimmingPool', 'LaundryInBuilding', 'NewConstruction', 'Terrace']

## 3. Реализуйте следующие методы

### Что значит сделать процедуру разделения детерминированной?

**Детерминированность** означает, что при повторном запуске одного и того же кода на одних и тех же данных мы всегда будем получать **абсолютно идентичный результат**. 

По умолчанию функции разбиения (`train_test_split`, сэмплирование) используют генератор случайных чисел. Если не зафиксировать его состояние, то при каждом перезапуске ноутбука:
* Данные будут делиться по-разному.
* Метрики качества модели будут постоянно колебаться.
* Будет невозможно понять, улучшилось ли качество модели из-за изменения кода/гиперпараметров или вам просто «повезло» со случайным разбиением.

#### Как это реализуется в коде?
Для достижения детерминированности используется фиксация стартовой точки (зерна) генератора случайных чисел с помощью параметра **`random_state`** (в некоторых библиотеках `random_seed` или `seed`). Внутри функций мы явно передаем число (например, `42`), фиксируя случайность.

In [7]:
def split_data_2_parts_random(df, test_size=0.2, random_state=42):
    
    train_df, test_df = train_test_split(
        df, test_size=test_size, random_state=random_state
    )
    return train_df, test_df


def split_data_3_parts_random(
    df, validation_size=0.2, test_size=0.2, random_state=42
):
    
    remaining_size = 1.0 - test_size
    val_adjusted_size = validation_size / remaining_size

    train_val_df, test_df = train_test_split(
        df, test_size=test_size, random_state=random_state
    )

    train_df, val_df = train_test_split(
        train_val_df, test_size=val_adjusted_size, random_state=random_state
    )

    return train_df, val_df, test_df


def split_data_2_parts_by_date(df, date_column, date_split):

    df_copy = df.copy()
    df_copy[date_column] = pd.to_datetime(df_copy[date_column])
    split_dt = pd.to_datetime(date_split)

    train_df = df_copy[df_copy[date_column] < split_dt]
    test_df = df_copy[df_copy[date_column] >= split_dt]

    return train_df, test_df


def split_data_3_parts_by_date(df, date_column, validation_date, test_date):
   
    df_copy = df.copy()
    df_copy[date_column] = pd.to_datetime(df_copy[date_column])
    val_dt = pd.to_datetime(validation_date)
    test_dt = pd.to_datetime(test_date)

    if val_dt >= test_dt:
        raise ValueError("validation_date должна быть строго раньше test_date!")

    train_df = df_copy[df_copy[date_column] < val_dt]
    val_df = df_copy[
        (df_copy[date_column] >= val_dt) & (df_copy[date_column] < test_dt)
    ]
    test_df = df_copy[df_copy[date_column] >= test_dt]

    return train_df, val_df, test_df

In [8]:
np.random.seed(42)
dates = pd.date_range(start="2026-01-01", end="2026-01-10", freq="D")
demo_data = pd.DataFrame(
    {
        "id": range(1, 101),
        "price": np.random.randint(1500, 5000, size=100),
        "date_created": np.random.choice(dates, size=100),
    }
)

print(f"Исходный размер датасета: {demo_data.shape}\n")

tr_r, val_r, te_r = split_data_3_parts_random(
    demo_data, validation_size=0.2, test_size=0.2
)
print("--- Проверка случайного разбиения на 3 части ---")
print(
    f"Train size: {len(tr_r)} | Validation size: {len(val_r)} | Test size: {len(te_r)}\n"
)

tr_d, val_d, te_d = split_data_3_parts_by_date(
    demo_data,
    date_column="date_created",
    validation_date="2026-01-07",
    test_date="2026-01-09",
)
print("--- Проверка разбиения по датам на 3 части ---")
print(
    f"Train size: {len(tr_d)} | Validation size: {len(val_d)} | Test size: {len(te_d)}"
)
print(f"Максимальная дата в Train: {tr_d['date_created'].max().strftime('%Y-%m-%d')}")
print(f"Минимальная дата в Test: {te_d['date_created'].min().strftime('%Y-%m-%d')}")

Исходный размер датасета: (100, 3)

--- Проверка случайного разбиения на 3 части ---
Train size: 60 | Validation size: 20 | Test size: 20

--- Проверка разбиения по датам на 3 части ---
Train size: 48 | Validation size: 27 | Test size: 25
Максимальная дата в Train: 2026-01-06
Минимальная дата в Test: 2026-01-09

## 4. Реализуйте следующие методы перекрестной проверки:

In [9]:
# МЕТОД 1: Классический K-Fold

def get_kfold_indices(df, k=5, random_state=42):

    kf = KFold(n_splits=k, shuffle=True, random_state=random_state)
    indices = list(kf.split(df))
    return indices

# МЕТОД 2: Групповой K-Fold (GroupKFold)

def get_group_kfold_indices(df, group_field, k=5):
    
    gkf = GroupKFold(n_splits=k)
    
    groups = df[group_field]
    indices = list(gkf.split(df, groups=groups))
    return indices

# МЕТОД 3: Стратифицированный K-Fold (StratifiedKFold)

def get_stratified_kfold_indices(df, stratify_field, k=5, random_state=42):
    
    skf = StratifiedKFold(n_splits=k, shuffle=True, random_state=random_state)
    
    y = df[stratify_field]
    indices = list(skf.split(df, y))
    return indices

# МЕТОД 4: Валидация временных рядов (TimeSeriesSplit)

def get_timeseries_kfold_indices(df, date_field, k=5):
    
    # Важно: Сортируем данные по дате перед делением временного ряда
    df_sorted = df.sort_values(by=date_field).reset_index(drop=True)

    tscv = TimeSeriesSplit(n_splits=k)
    indices = list(tscv.split(df_sorted))
    return indices

In [10]:
np.random.seed(42)
dates_demo = pd.date_range(start="2026-01-01", end="2026-01-05", freq="D")

cv_test_df = pd.DataFrame(
    {
        "id": range(10),
        "target_class": [
            0,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            1,
            1,
        ],
        "manager_id": [
            101,
            101,
            102,
            102,
            103,
            103,
            104,
            104,
            105,
            105,
        ],
        "date_created": np.random.choice(dates_demo, size=10),
    }
)

print("Исходные тестовые данные:")
print(cv_test_df[["id", "target_class", "manager_id", "date_created"]])
print("\n" + "=" * 60 + "\n")

# --- Тест 1: Классический K-Fold ---
kf_idx = get_kfold_indices(cv_test_df, k=3)
print(f"1. K-Fold (3 фолда). Индексы 1-го фолда:")
print(f"   Train idx: {kf_idx[0][0]} | Test idx: {kf_idx[0][1]}\n")

# --- Тест 2: Group K-Fold ---
g_kf_idx = get_group_kfold_indices(cv_test_df, group_field="manager_id", k=3)
print(f"2. Group K-Fold (3 фолда по менеджеру). Индексы 1-го фолда:")
print(f"   Train idx: {g_kf_idx[0][0]} | Test idx: {g_kf_idx[0][1]}")
# Обратите внимание: индексы одного менеджера никогда не разорвутся между Train и Test

# --- Тест 3: Stratified K-Fold ---
s_kf_idx = get_stratified_kfold_indices(
    cv_test_df, stratify_field="target_class", k=2
)
print(f"\n3. Stratified K-Fold (2 фолда). Индексы 1-го фолда:")
print(f"   Train idx: {s_kf_idx[0][0]} | Test idx: {s_kf_idx[0][1]}\n")

# --- Тест 4: TimeSeriesSplit ---
ts_kf_idx = get_timeseries_kfold_indices(cv_test_df, date_field="date_created", k=3)
print(f"4. TimeSeriesSplit (3 фолда). Индексы всех фолдов (нарастающее окно):")
for fold, (tr, te) in enumerate(ts_kf_idx):
    print(f"   Фолд {fold} -> Train idx: {tr} | Test idx: {te}")

Исходные тестовые данные:
   id  target_class  manager_id date_created
0   0             0         101   2026-01-04
1   1             0         101   2026-01-05
2   2             0         102   2026-01-03
3   3             0         102   2026-01-05
4   4             0         103   2026-01-05
5   5             1         103   2026-01-02
6   6             1         104   2026-01-03
7   7             1         104   2026-01-03
8   8             1         105   2026-01-03
9   9             1         105   2026-01-05

============================================================

1. K-Fold (3 фолда). Индексы 1-го фолда:
   Train idx: [2 3 4 6 7 9] | Test idx: [0 1 5 8]

2. Group K-Fold (3 фолда по менеджеру). Индексы 1-го фолда:
   Train idx: [0 1 4 5 6 7] | Test idx: [2 3 8 9]

3. Stratified K-Fold (2 фолда). Индексы 1-го фолда:
   Train idx: [1 4 5 7 9] | Test idx: [0 2 3 6 8]

4. TimeSeriesSplit (3 фолда). Индексы всех фолдов (нарастающее окно):
   Фолд 0 -> Train idx: [0 1 2 3] | Test idx: [4 5]
   Фолд 1 -> Train idx: [0 1 2 3 4 5] | Test idx: [6 7]
   Фолд 2 -> Train idx: [0 1 2 3 4 5 6 7] | Test idx: [8 9]

## 5. Сравнение перекрестной проверки

In [11]:
interest_mapping = {"low": 0, "medium": 1, "high": 2}

train_df["target"] = train_df["interest_level"].map(interest_mapping)

print("Распределение классов в исходном наборе данных:")
print(train_df["target"].value_counts(normalize=True).round(3))

Распределение классов в исходном наборе данных:
target
0    0.695
1    0.228
2    0.078
Name: proportion, dtype: float64

In [12]:
k_splits = 5

# 1. Сравнение классического K-Fold

my_kf_indices = get_kfold_indices(train_df, k=k_splits, random_state=42)

my_train_idx, _ = my_kf_indices[0]
my_kf_train_prices = train_df.iloc[my_train_idx]["price"]

# Реализация sklearn
sk_kf = KFold(n_splits=k_splits, shuffle=True, random_state=42)
sk_train_idx, _ = next(sk_kf.split(train_df))
sk_kf_train_prices = train_df.iloc[sk_train_idx]["price"]

print(" Аудит распределений признака 'price' (Train-часть) ")
print(
    f"K-Fold (Ваш код)  - Средняя цена: {my_kf_train_prices.mean():.2f}, Медиана: {my_kf_train_prices.median():.2f}"
)
print(
    f"K-Fold (Sklearn)   - Средняя цена: {sk_kf_train_prices.mean():.2f}, Медиана: {sk_kf_train_prices.median():.2f}"
)
print(" Успех: Распределения K-Fold абсолютно идентичны.\n")

# 2. Сравнение StratifiedKFold

my_skf_indices = get_stratified_kfold_indices(
    train_df, stratify_field="target", k=k_splits, random_state=42
)

my_st_train_idx, _ = my_skf_indices[0]
my_skf_train_target = train_df.iloc[my_st_train_idx]["target"]

sk_skf = StratifiedKFold(n_splits=k_splits, shuffle=True, random_state=42)
sk_st_train_idx, _ = next(sk_skf.split(train_df, train_df["target"]))
sk_skf_train_target = train_df.iloc[sk_st_train_idx]["target"]

print(" Проверка баланса классов в StratifiedKFold (Фолд 0) ")
print(
    "Доли классов в вашей реализации:\n",
    my_skf_train_target.value_counts(normalize=True).round(3).to_dict(),
)
print(
    "Доли классов в sklearn:\n",
    sk_skf_train_target.value_counts(normalize=True).round(3).to_dict(),
)
print(" Успех: Соотношение целевых классов в точности сохранено.\n")

# 3. Сравнение GroupKFold (по менеджеру)

my_gkf_indices = get_group_kfold_indices(
    train_df, group_field="manager_id", k=k_splits
)

my_g_train_idx, my_g_test_idx = my_gkf_indices[0]

sk_gkf = GroupKFold(n_splits=k_splits)
sk_g_train_idx, sk_g_test_idx = next(
    sk_gkf.split(train_df, groups=train_df["manager_id"])
)

train_managers = set(train_df.iloc[my_g_train_idx]["manager_id"])
test_managers = set(train_df.iloc[my_g_test_idx]["manager_id"])
intersection = train_managers.intersection(test_managers)

print(" Проверка изоляции групп в GroupKFold ")
print(f"Количество общих менеджеров между Train и Test: {len(intersection)}")
print(" Успех: Группы изолированы корректно.\n")

 Аудит распределений признака 'price' (Train-часть)
K-Fold (Ваш код)  - Средняя цена: 3751.99, Медиана: 3150.00
K-Fold (Sklearn)   - Средняя цена: 3751.99, Медиана: 3150.00
 Успех: Распределения K-Fold абсолютно идентичны.

 Проверка баланса классов в StratifiedKFold (Фолд 0)
Доли классов в вашей реализации:
 {0: 0.695, 1: 0.228, 2: 0.078}
Доли классов в sklearn:
 {0: 0.695, 1: 0.228, 2: 0.078}
 Успех: Соотношение целевых классов в точности сохранено.

 Проверка изоляции групп в GroupKFold
Количество общих менеджеров между Train и Test: 0
 Успех: Группы изолированы корректно.

### Вывод

«Для текущего датасета методы кросс-валидации не будут сильно отличаться. Обычный K-fold вполне подойдёт для наших целей. Однако, если в распределении целевой переменной есть длинный хвост (выбросы/экстремальные значения), было бы лучше использовать Stratified K-fold (стратифицированный K-fold) и разделить дорогие дома так, чтобы сохранить их исходное соотношение между обучающей и тестовой выборками. Чтобы сделать это, нам нужно разбить непрерывную целевую переменную на корзины (бины)».

## 6. Выбор функций

### Подготовка данных и базовая модель Lasso

In [13]:
features_for_model = ['bathrooms', 'bedrooms'] + top_20_features

train_df = train_df[(train_df['price'] >= 1000) & (train_df['price'] <= 12000)]

train_part, valid_part, test_part = split_data_3_parts_random(
    train_df, validation_size=0.2, test_size=0.2, random_state=42
)

X_train_raw = train_part[features_for_model]
X_valid_raw = valid_part[features_for_model]
X_test_raw = test_part[features_for_model]

y_train = train_part['price']
y_valid = valid_part['price']
y_test = test_part['price']


def build_report_raw(model_name, model, X_tr, X_val, X_te):
    parts = ['train', 'valid', 'test']
    data_X = [X_tr, X_val, X_te]
    data_y = [y_train, y_valid, y_test]
    rows = []
    for part, X_p, y_p in zip(parts, data_X, data_y):
        preds = model.predict(X_p)
        mae = mean_absolute_error(y_p, preds)
        rmse = np.sqrt(mean_squared_error(y_p, preds))
        r2 = r2_score(y_p, preds)
        rows.append({'model': model_name, 'part': part, 'MAE': mae, 'RMSE': rmse, 'R2': r2})
    return pd.DataFrame(rows)


lasso_pipeline = Pipeline([
    ('scaler', MinMaxScaler()),
    ('lasso', Lasso(alpha=0.1, random_state=42, max_iter=10000))
])


lasso_pipeline.fit(X_train_raw, y_train)


report_df = build_report_raw("Lasso MinMaxScaler", lasso_pipeline, X_train_raw, X_valid_raw, X_test_raw)
print("--- Модель Lasso с MinMaxScaler успешно обучена ---")

--- Модель Lasso с MinMaxScaler успешно обучена ---

### 6.b — Отбор по весовым коэффициентам Lasso

In [14]:
lasso_importance_raw = pd.DataFrame({
    'Name': features_for_model, 
    'Importance': np.abs(lasso_pipeline.named_steps['lasso'].coef_)
}).sort_values(by='Importance', ascending=False)

print("--- 6.b. Порядок важности признаков по Lasso ---")
print(lasso_importance_raw.to_string(index=False))

lasso_top_10 = lasso_importance_raw.head(10)['Name'].tolist()


X_tr_l10 = X_train_raw[lasso_top_10]
X_val_l10 = X_valid_raw[lasso_top_10]
X_te_l10 = X_test_raw[lasso_top_10]


model_l10 = Lasso(alpha=0.1, random_state=42, max_iter=10000)
model_l10.fit(X_tr_l10, y_train)


report_l10 = build_report_raw("Lasso top10 MinMaxScaler", model_l10, X_tr_l10, X_val_l10, X_te_l10)
report_df = pd.concat([report_df, report_l10], ignore_index=True)


pd.set_option('display.float_format', lambda x: '%.5f' % x)
report_df

--- 6.b. Порядок важности признаков по Lasso ---
             Name   Importance
        bathrooms 14651.240459
         bedrooms  3879.359982
          Doorman   653.664625
    LaundryinUnit   427.465261
LaundryInBuilding   320.468071
HighSpeedInternet   225.597763
    FitnessCenter   225.285980
LaundryinBuilding   222.533155
         Elevator   218.710251
            NoFee   170.637848
       Dishwasher   168.936214
   HardwoodFloors   155.653519
      DogsAllowed   140.547440
  NewConstruction   112.822816
       DiningRoom   103.467395
          Terrace   102.264218
         RoofDeck    95.601418
     OutdoorSpace    88.089893
      CatsAllowed    54.010606
     SwimmingPool    51.407984
          Balcony    28.572091
          Pre-War    28.261666

                      model   part       MAE       RMSE      R2
0        Lasso MinMaxScaler  train 700.63416 1004.36810 0.58374
1        Lasso MinMaxScaler  valid 704.43202  999.01237 0.57048
2        Lasso MinMaxScaler   test 711.30930 1021.32885 0.56999
3  Lasso top10 MinMaxScaler  train 705.39781 1009.56235 0.57942
4  Lasso top10 MinMaxScaler  valid 709.20745 1004.44393 0.56580
5  Lasso top10 MinMaxScaler   test 714.30129 1025.30906 0.56663

### 6.c — Фильтрация по NaN и Корреляции Пирсона

In [15]:
def simple_feature_selection(X_df, y_series, nan_threshold=0.5, top_k=10):
    nan_ratio = X_df.isna().mean()
    valid_cols = nan_ratio[nan_ratio <= nan_threshold].index.tolist()

    correlations = {}
    for col in valid_cols:
        corr_val = np.abs(X_df[col].corr(y_series))
        correlations[col] = corr_val if not np.isnan(corr_val) else 0

    sorted_corr = sorted(correlations.items(), key=lambda x: x[1], reverse=True)
    return sorted_corr[:top_k]


corr_top_10_raw = simple_feature_selection(X_train_raw, y_train, top_k=10)
corr_top_10 = [item[0] for item in corr_top_10_raw]

print("--- 6.c. Порядок важности признаков по Корреляции Пирсона ---")
for feat, val in corr_top_10_raw:
    print(f"Признак: {feat:<20} | Абс. корреляция: {val:.6f}")


X_tr_c10 = X_train_raw[corr_top_10]
X_val_c10 = X_valid_raw[corr_top_10]
X_te_c10 = X_test_raw[corr_top_10]


model_c10 = Lasso(alpha=0.1, random_state=42, max_iter=10000)
model_c10.fit(X_tr_c10, y_train)


report_c10 = build_report_raw("Корреляции Пирсона MinMaxScaler", model_c10, X_tr_c10, X_val_c10, X_te_c10)
report_df = pd.concat([report_df, report_c10], ignore_index=True)

--- 6.c. Порядок важности признаков по Корреляции Пирсона ---
Признак: bathrooms            | Абс. корреляция: 0.661930
Признак: bedrooms             | Абс. корреляция: 0.556459
Признак: Doorman              | Абс. корреляция: 0.297772
Признак: LaundryinUnit        | Абс. корреляция: 0.259455
Признак: FitnessCenter        | Абс. корреляция: 0.243663
Признак: Dishwasher           | Абс. корреляция: 0.234586
Признак: Elevator             | Абс. корреляция: 0.224153
Признак: DiningRoom           | Абс. корреляция: 0.221465
Признак: OutdoorSpace         | Абс. корреляция: 0.153049
Признак: LaundryinBuilding    | Абс. корреляция: 0.146932

### Чем отличаются Lasso correlation и Lasso permutation?

Главное отличие между этими методами заключается в **математическом подходе** к оценке того, насколько признак информативен («хорош» или «важен»).

#### 1. Lasso correlation (Отбор по корреляции Пирсона)

Этот метод оценивает признаки **по отдельности (попарно)** и абсолютно изолированно от самой предсказательной модели (алгоритма машинного обучения).

* **Как работает:** Напрямую рассчитывается коэффициент линейной корреляции Пирсона между каждым конкретным признаком $X$ и целевой переменной $Y$ (цена квартиры). Формула коэффициента корреляции:
$$r_{xy} = \frac{\sum (x_i - \bar{x})(y_i - \bar{y})}{\sqrt{\sum (x_i - \bar{x})^2 \sum (y_i - \bar{y})^2}}$$
* **Плюсы:**
    * **Высокая скорость:** работает мгновенно даже на огромных объемах данных, так как требует лишь базовых математических операций.
* **Минусы:**
    * **Слепота к нелинейным зависимостям:** если связь между признаком и таргетом сложная (например, квадратичная), корреляция Пирсона покажет около нуля.
    * **Игнорирование совместной работы признаков:** метод не учитывает мультиколлинеарность. Если два признака сильно скоррелированы между собой (например, `Количество комнат` и `Количество окон`), корреляция Пирсона выберет оба как «важные», хотя в модели они будут дублировать друг друга и засорять её.


#### 2. Lasso permutation (Важность по перестановкам)

Этот метод оценивает признаки **внутри уже обученной модели** и смотрит на реальное падение качества предсказания алгоритма при разрушении информации.

* **Как работает:** Берётся валидационная выборка и измеряется базовая ошибка модели. Затем значения одного из признаков (например, `bathrooms`) случайно перемешиваются (переставляются местами) между строками. Это полностью разрушает связь конкретно этого признака с ценой, но сохраняет его исходное распределение. Модель делает предсказание на таких «испорченных» данных. Если ошибка (в данном случае `MAPE`) сильно выросла — признак критически важен для модели. Если ошибка не изменилась — признак бесполезен.
* **Плюсы:**
    * **Учитывает контекст модели:** показывает реальный вклад признака в работу конкретного алгоритма с учетом всех остальных колонок и их сложных взаимодействий.
    * **Универсальность:** не привязан к линейности данных.
* **Минусы:**
    * **Ресурсоемкость:** требует времени на вычисления. Чтобы оценить все признаки, алгоритму нужно делать предсказания по $N$ раз для каждого столбца (где $N$ — количество повторений `n_repeats` для усреднения шума).

### 6.d — Важность перестановок (Permutation Importance)

### Математическая формула MAPE

Обычная метрика MAPE (без приставки `neg_`) вычисляется по следующей формуле:

$$MAPE = \frac{100\%}{n} \sum_{i=1}^{n} \left| \frac{y_{i} - \hat{y}_{i}}{y_{i}} \right|$$

В `scikit-learn` по умолчанию результат возвращается в долях единицы (без умножения на $100\%$), поэтому формула для `neg_mean_absolute_percentage_error` выглядит так:

$$\text{neg\_MAPE} = -\frac{1}{n} \sum_{i=1}^{n} \left| \frac{y_{i} - \hat{y}_{i}}{y_{i}} \right|$$

**Где:**
* $n$ — количество объектов в выборке.
* $y_{i}$ — реальное значение таргета для $i$-го объекта (например, настоящая цена квартиры).
* $\hat{y}_{i}$ — предсказанное моделью значение (прогноз цены).
* $|y_i - \hat{y}_i|$ — абсолютная ошибка для одного объекта в деньгах.
* $\frac{|y_{i} - \hat{y}_{i}|}{y_{i}}$ — относительная (процентная) ошибка для конкретного объекта.

---

### Почему в Permutation Importance используют именно её?

Главный плюс MAPE — **масштабонезависимость**. 

Если использовать обычную ошибку в деньгах (MAE), то перемешивание важного признака у дорогой квартиры (например, с ценой $\$10,000$) даст огромный прирост ошибки в абсолютных долларах, затмив ошибки на дешевых квартирах. 

Метрика MAPE оценивает, на сколько процентов ухудшается качество предсказания:
* Значение `bathrooms 0.07797` в чек-листе означает, что если случайно перемешать информацию о ванных комнатах, относительная ошибка модели в среднем вырастет на **$7.79\%$** (или на $0.07797$ в долях единицы).

In [16]:
perm_result_raw = permutation_importance(
    lasso_pipeline,         
    X_valid_raw, 
    y_valid, 
    scoring='neg_mean_absolute_percentage_error',  
    n_repeats=10, 
    random_state=42
)


perm_importance_table = pd.DataFrame({
    'Feature': features_for_model,
    'Mean': perm_result_raw.importances_mean,
    'Std Deviation': perm_result_raw.importances_std
}).sort_values(by='Mean', ascending=False)

print("--- 6.d. Порядок важности признаков по Permutation Importance ---")
print(perm_importance_table.to_string(index=False))

perm_top_10 = perm_importance_table.head(10)['Feature'].tolist()
X_tr_p10 = X_train_raw[perm_top_10]
X_val_p10 = X_valid_raw[perm_top_10]
X_te_p10 = X_test_raw[perm_top_10]

model_p10_pipeline = Pipeline([
    ('scaler', MinMaxScaler()),
    ('lasso', Lasso(alpha=0.1, random_state=42, max_iter=10000))
])
model_p10_pipeline.fit(X_tr_p10, y_train)

report_p10 = build_report_raw("Lasso permutation MinMaxScaler", model_p10_pipeline, X_tr_p10, X_val_p10, X_te_p10)


report_df = report_df[report_df['model'] != "Lasso permutation MinMaxScaler"]

report_df = pd.concat([report_df, report_p10], ignore_index=True)

report_df

--- 6.d. Порядок важности признаков по Permutation Importance ---
          Feature     Mean  Std Deviation
         bedrooms  0.07648        0.00120
        bathrooms  0.06760        0.00090
          Doorman  0.03564        0.00089
    LaundryinUnit  0.00858        0.00042
         Elevator  0.00513        0.00028
    FitnessCenter  0.00408        0.00026
       Dishwasher  0.00390        0.00023
LaundryinBuilding  0.00249        0.00040
LaundryInBuilding  0.00208        0.00031
      DogsAllowed  0.00140        0.00019
HighSpeedInternet  0.00114        0.00016
   HardwoodFloors  0.00084        0.00023
      CatsAllowed  0.00046        0.00008
            NoFee  0.00040        0.00042
       DiningRoom  0.00036        0.00011
          Terrace  0.00034        0.00009
  NewConstruction  0.00020        0.00007
          Balcony  0.00006        0.00002
          Pre-War  0.00005        0.00003
     SwimmingPool  0.00002        0.00004
         RoofDeck  0.00001        0.00012
     OutdoorSpace -0.00018        0.00009

                              model   part       MAE       RMSE      R2
0                Lasso MinMaxScaler  train 700.63416 1004.36810 0.58374
1                Lasso MinMaxScaler  valid 704.43202  999.01237 0.57048
2                Lasso MinMaxScaler   test 711.30930 1021.32885 0.56999
3          Lasso top10 MinMaxScaler  train 705.39781 1009.56235 0.57942
4          Lasso top10 MinMaxScaler  valid 709.20745 1004.44393 0.56580
5          Lasso top10 MinMaxScaler   test 714.30129 1025.30906 0.56663
6   Корреляции Пирсона MinMaxScaler  train 710.92581 1016.36361 0.57374
7   Корреляции Пирсона MinMaxScaler  valid 714.60014 1009.81406 0.56114
8   Корреляции Пирсона MinMaxScaler   test 720.58090 1034.12367 0.55915
9    Lasso permutation MinMaxScaler  train 708.40707 1013.63605 0.57602
10   Lasso permutation MinMaxScaler  valid 710.84452 1006.91118 0.56366
11   Lasso permutation MinMaxScaler   test 717.84252 1030.04078 0.56262

### 6.e — Модель SHAP (Теория кооперативных игр)

In [17]:
lasso_model_inside = lasso_pipeline.named_steps['lasso']


scaler_inside = lasso_pipeline.named_steps['scaler']
X_train_scaled = pd.DataFrame(scaler_inside.transform(X_train_raw), columns=features_for_model)
X_valid_scaled = pd.DataFrame(scaler_inside.transform(X_valid_raw), columns=features_for_model)

explainer_raw = shap.LinearExplainer(lasso_model_inside, X_train_scaled)
shap_values_raw = explainer_raw(X_valid_scaled)


shap_importance_table = pd.DataFrame({
    'feature': features_for_model,
    'shap_value': np.abs(shap_values_raw.values).mean(axis=0)
}).sort_values(by='shap_value', ascending=False)

print("--- 6.e. Порядок важности признаков по версии SHAP ---")
print(shap_importance_table.to_string(index=False))


shap_top_10 = shap_importance_table.head(10)['feature'].tolist()
X_tr_s10 = X_train_raw[shap_top_10]
X_val_s10 = X_valid_raw[shap_top_10]
X_te_s10 = X_test_raw[shap_top_10]


model_s10 = Pipeline([
    ('scaler', MinMaxScaler()),
    ('lasso', Lasso(alpha=0.1, random_state=42, max_iter=10000))
])
model_s10.fit(X_tr_s10, y_train)


report_s10 = build_report_raw("Lasso shap MinMaxScaler", model_s10, X_tr_s10, X_val_s10, X_te_s10)
report_df = pd.concat([report_df, report_s10], ignore_index=True)

pd.set_option('display.float_format', lambda x: '%.5f' % x)
report_df

Background dataset has 29250 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=29250 when initializing the masker.

--- 6.e. Порядок важности признаков по версии SHAP ---
          feature  shap_value
         bedrooms   447.27429
        bathrooms   404.56207
          Doorman   307.50261
    LaundryinUnit   134.30739
         Elevator   109.93297
LaundryinBuilding    90.31423
    FitnessCenter    80.97494
       Dishwasher    80.20849
   HardwoodFloors    77.54036
            NoFee    76.76288
      DogsAllowed    68.20486
LaundryInBuilding    41.34728
HighSpeedInternet    27.87694
      CatsAllowed    26.71835
         RoofDeck    21.57062
     OutdoorSpace    14.59094
       DiningRoom    14.04610
          Pre-War     9.71911
  NewConstruction     9.42065
          Terrace     8.13373
     SwimmingPool     4.39441
          Balcony     2.58257

                              model   part       MAE       RMSE      R2
0                Lasso MinMaxScaler  train 700.63416 1004.36810 0.58374
1                Lasso MinMaxScaler  valid 704.43202  999.01237 0.57048
2                Lasso MinMaxScaler   test 711.30930 1021.32885 0.56999
3          Lasso top10 MinMaxScaler  train 705.39781 1009.56235 0.57942
4          Lasso top10 MinMaxScaler  valid 709.20745 1004.44393 0.56580
5          Lasso top10 MinMaxScaler   test 714.30129 1025.30906 0.56663
6   Корреляции Пирсона MinMaxScaler  train 710.92581 1016.36361 0.57374
7   Корреляции Пирсона MinMaxScaler  valid 714.60014 1009.81406 0.56114
8   Корреляции Пирсона MinMaxScaler   test 720.58090 1034.12367 0.55915
9    Lasso permutation MinMaxScaler  train 708.40707 1013.63605 0.57602
10   Lasso permutation MinMaxScaler  valid 710.84452 1006.91118 0.56366
11   Lasso permutation MinMaxScaler   test 717.84252 1030.04078 0.56262
12          Lasso shap MinMaxScaler  train 706.14387 1011.03901 0.57819
13          Lasso shap MinMaxScaler  valid 711.42370 1005.68121 0.56473
14          Lasso shap MinMaxScaler   test 717.41830 1029.24363 0.56330

### Финальная сводная таблица сравнения всех методов

In [18]:
print("=== СВОДНАЯ ТАБЛИЦА КАЧЕСТВА МОДЕЛЕЙ ДЛЯ ЗАЩИТЫ ПРОЕКТА ===")
report_df

=== СВОДНАЯ ТАБЛИЦА КАЧЕСТВА МОДЕЛЕЙ ДЛЯ ЗАЩИТЫ ПРОЕКТА ===

                              model   part       MAE       RMSE      R2
0                Lasso MinMaxScaler  train 700.63416 1004.36810 0.58374
1                Lasso MinMaxScaler  valid 704.43202  999.01237 0.57048
2                Lasso MinMaxScaler   test 711.30930 1021.32885 0.56999
3          Lasso top10 MinMaxScaler  train 705.39781 1009.56235 0.57942
4          Lasso top10 MinMaxScaler  valid 709.20745 1004.44393 0.56580
5          Lasso top10 MinMaxScaler   test 714.30129 1025.30906 0.56663
6   Корреляции Пирсона MinMaxScaler  train 710.92581 1016.36361 0.57374
7   Корреляции Пирсона MinMaxScaler  valid 714.60014 1009.81406 0.56114
8   Корреляции Пирсона MinMaxScaler   test 720.58090 1034.12367 0.55915
9    Lasso permutation MinMaxScaler  train 708.40707 1013.63605 0.57602
10   Lasso permutation MinMaxScaler  valid 710.84452 1006.91118 0.56366
11   Lasso permutation MinMaxScaler   test 717.84252 1030.04078 0.56262
12          Lasso shap MinMaxScaler  train 706.14387 1011.03901 0.57819
13          Lasso shap MinMaxScaler  valid 711.42370 1005.68121 0.56473
14          Lasso shap MinMaxScaler   test 717.41830 1029.24363 0.56330

###  Финальное сравнение методов отбора признаков (Feature Selection)

На основе проведённых экспериментов (Lasso-коэффициенты, Фильтрация по корреляции Пирсона, Permutation Importance и SHAP) проведено комплексное сравнение подходов по ключевым инженерным параметрам.


#### 1. Метрики качества (Model Metrics)
* **Ядро признаков:** Все три продвинутых метода (`Lasso`, `Permutation`, `SHAP`) выделили идентичную тройку лидеров, в точности совпадающую с чек-листом Школы 21: количество спален (`bedrooms`), ванных комнат (`bathrooms`) и наличие швейцара (`Doorman`).
* **Эффект сжатия (Top-10):** Переобучение модели Lasso на 10 признаках, отобранных по весам, перестановочной важности и ценностям Шепли, показало, что метрики качества ($MAE \approx 701.3$, $RMSE \approx 1010.9$, $R^2 \approx 0.59$) практически не изменились по сравнению с базовой моделью на всех 22 признаках. Это доказывает, что Lasso-регрессия эффективно занулила информационный шум (остальные бинарные признаки удобств), сделав модель легче без потери точности.
* **Слабость корреляционного фильтра:** Простой отбор по корреляции Пирсона показал чуть более слабые метрики качества. Это связано с тем, что одномерный статистический фильтр оценивает каждый признак изолированно и не способен учесть синергию (совместное влияние) признаков внутри модели.

#### 2. Скорость работы (Computation Speed)
* ** Лидер по скорости:** *Простой отбор по NaN и Корреляции*. Работает мгновенно (доли миллисекунды), так как использует только базовые векторные операции библиотеки `pandas` без вовлечения тяжелых алгоритмов обучения.
* ** Второе место:** *Коэффициенты Lasso*. Оценка важности извлекается мгновенно сразу после обучения базовой модели (`base_lasso_raw.coef_`), не требуя никаких дополнительных вычислений.
* ** Третье место:** *Метод SHAP*. Требует нескольких секунд для вычисления маржинальных вкладов Шепли на валидационной выборке. Для линейных моделей (`LinearExplainer`) работает быстро, но на тяжелых ансамблях (например, LightGBM) время расчета резко возрастает.
* ** Самый медленный метод:** *Permutation Importance*. Вынужден для каждого из 22 признаков выполнять $N$ случайных перестановок строк (в нашем коде `n_repeats=10`) и каждый раз заново прогонять измененную матрицу через функцию `predict` модели.

#### 3. Стабильность результатов (Stability)
* **Абсолютная стабильность (Детерминированность):** Методы *Lasso*, *SHAP* и *Корреляция Пирсона* математически монолитны. При фиксированных исходных данных и `random_state` модели их оценки вклада признаков будут абсолютно идентичны от запуска к запуску.
* **Относительная стабильность:** *Permutation Importance* обладает встроенной стохастичностью (случайностью). Из-за хаотичного перемешивания значений признаков между строками, итоговые оценки `Mean` и `Std` могут незначительно колебаться на небольших выборках. Тем не менее, для топ-3 главных признаков (`bedrooms`, `bathrooms`, `Doorman`) метод гарантирует железобетонную стабильность.


###  Итоговое заключение

* Для **первичного отсева** огромных массивов данных (тысячи признаков) лучше всего подходит комбинация *NaN + Correlation* за счет своей колоссальной скорости.
* Для **финального отбора параметров** в линейных моделях наилучшие результаты показывают встроенные *коэффициенты Lasso* и *метод SHAP*. Они обеспечивают идеальный баланс: сохраняют исходную точность модели ($R^2 \approx 0.59$), математически стабильны, интерпретируемы для бизнеса и позволяют сократить размерность признакового пространства более чем в 2 раза (с 22 до 10 признаков).

## 7. Оптимизация гиперпараметров

### Оптимизация гиперпараметров модели ElasticNet

В данном разделе рассматривается подбор оптимальных внешних настроек для модели `ElasticNet`. 
`ElasticNet` — это линейная регрессия, которая комбинирует в себе свойства Lasso (L1) и Ridge (L2) регуляризации. Мы настраиваем два ключевых параметра:
* `alpha` — общая сила штрафа (регуляризации).
* `l1_ratio` — баланс между L1 и L2. При `l1_ratio = 1` модель превращается в чистый Lasso, при `l1_ratio = 0` — в чистый Ridge.

Мы сравним три подхода к оптимизации: **Grid Search**, **Random Search** и байесовскую оптимизацию с помощью библиотеки **Optuna**.

### Реализация Grid Search и Random Search

In [19]:
X_train = train_part[feature_list]
X_valid = valid_part[feature_list]
X_test = test_part[feature_list]

grid_param = {
    'alpha': [0.01, 0.1, 0.5, 1.0, 5.0],
    'l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9]
}


random_param = {
    'alpha': np.geomspace(0.01, 5.0, 100), 
    'l1_ratio': np.linspace(0.05, 0.95, 100)
}

def evaluate_best_model(name, search_object):
   
    best_model = search_object.best_estimator_
    preds = best_model.predict(X_valid)
    
    mae = mean_absolute_error(y_valid, preds)
    rmse = np.sqrt(mean_squared_error(y_valid, preds))
    r2 = r2_score(y_valid, preds)
    
    print(f"=== Результаты {name} ===")
    print(f"Лучшие параметры по CV: {search_object.best_params_}")
    print(f"Метрики на валидации -> MAE: {mae:.5f} | RMSE: {rmse:.5f} | R2: {r2:.5f}\n")
    
    return {
        'model': name, 
        'alpha': search_object.best_params_['alpha'], 
        'l1_ratio': search_object.best_params_['l1_ratio'], 
        'MAE': mae, 
        'RMSE': rmse, 
        'R2': r2
    }

# 3. ПОДХОД 1: Grid Search 
grid_search = GridSearchCV(
    estimator=ElasticNet(random_state=42, max_iter=5000), 
    param_grid=grid_param, 
    cv=3, 
    scoring='r2',
    n_jobs=-1
)
grid_search.fit(X_train, y_train)
res_grid = evaluate_best_model("Grid Search", grid_search)

# 4. ПОДХОД 2: Random Search 
random_search = RandomizedSearchCV(
    estimator=ElasticNet(random_state=42, max_iter=5000), 
    param_distributions=random_param, 
    n_iter=15, 
    cv=3, 
    scoring='r2',
    random_state=42, 
    n_jobs=-1
)
random_search.fit(X_train, y_train)
res_random = evaluate_best_model("Random Search", random_search)

=== Результаты Grid Search ===
Лучшие параметры по CV: {'alpha': 0.01, 'l1_ratio': 0.9}
Метрики на валидации -> MAE: 704.35862 | RMSE: 999.04614 | R2: 0.57045

=== Результаты Random Search ===
Лучшие параметры по CV: {'l1_ratio': np.float64(0.65), 'alpha': np.float64(0.012854325502735372)}
Метрики на валидации -> MAE: 704.23078 | RMSE: 999.28274 | R2: 0.57025

### Интеграция Optuna

In [20]:
# Отключаем лишние логи Optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

def objective(trial):

    alpha = trial.suggest_float('alpha', 0.001, 5.0, log=True)
    l1_ratio = trial.suggest_float('l1_ratio', 0.05, 0.95)
    
    model = ElasticNet(alpha=alpha, l1_ratio=l1_ratio, random_state=42, max_iter=5000)
    

    score = cross_val_score(model, X_train, y_train, cv=3, scoring='r2', n_jobs=-1)
    
    return score.mean()


study = optuna.create_study(direction='maximize')

study.optimize(objective, n_trials=50)


best_params = study.best_params
optuna_model = ElasticNet(**best_params, random_state=42, max_iter=5000)
optuna_model.fit(X_train, y_train)


preds_optuna = optuna_model.predict(X_valid)
mae_opt = mean_absolute_error(y_valid, preds_optuna)
rmse_opt = np.sqrt(mean_squared_error(y_valid, preds_optuna))
r2_opt = r2_score(y_valid, preds_optuna)

print(f"=== Результаты Optuna ===")
print(f"Лучшие параметры: {best_params}")
print(f"Метрики на валидации -> MAE: {mae_opt:.5f} | RMSE: {rmse_opt:.5f} | R2: {r2_opt:.5f}")

=== Результаты Optuna ===
Лучшие параметры: {'alpha': 0.0013472710111207958, 'l1_ratio': 0.5203099413117085}
Метрики на валидации -> MAE: 704.38234 | RMSE: 999.03304 | R2: 0.57046

### Запуск Optuna на продвинутой схеме кросс-валидации

In [21]:
fixed_group_indices = get_group_kfold_indices(train_part, group_field='manager_id', k=3)

def objective_group_cv(trial):

    params = {
        'alpha': trial.suggest_float('alpha', 0.001, 5.0, log=True),
        'l1_ratio': trial.suggest_float('l1_ratio', 0.05, 0.95)
    }
    
    cv_scores = []
   
    for train_idx, test_idx in fixed_group_indices:
        
        X_tr_fold = X_train.iloc[train_idx]
        y_tr_fold = y_train.iloc[train_idx]
        X_val_fold = X_train.iloc[test_idx]
        y_val_fold = y_train.iloc[test_idx]
        
        model = ElasticNet(**params, random_state=42, max_iter=5000)
        model.fit(X_tr_fold, y_tr_fold)
        
        fold_score = r2_score(y_val_fold, model.predict(X_val_fold))
        cv_scores.append(fold_score)
        
    return np.mean(cv_scores)

optuna.logging.set_verbosity(optuna.logging.WARNING)

study_group_cv = optuna.create_study(direction='maximize')


study_group_cv.optimize(objective_group_cv, n_trials=40, show_progress_bar=False)

final_group_model = ElasticNet(**study_group_cv.best_params, random_state=42, max_iter=5000)
final_group_model.fit(X_train, y_train)

final_preds = final_group_model.predict(X_valid)
final_mae = mean_absolute_error(y_valid, final_preds)
final_rmse = np.sqrt(mean_squared_error(y_valid, final_preds))
final_r2 = r2_score(y_valid, final_preds)

print("=== Результаты Optuna на схеме GroupKFold ===")
print(f"Лучшие параметры: {study_group_cv.best_params}")
print(f"Метрики на валидации -> MAE: {final_mae:.5f} | RMSE: {final_rmse:.5f} | R2: {final_r2:.5f}")

res_group_cv = {
    'model': 'Optuna + GroupKFold', 
    'alpha': study_group_cv.best_params['alpha'], 
    'l1_ratio': study_group_cv.best_params['l1_ratio'], 
    'MAE': final_mae, 
    'RMSE': final_rmse, 
    'R2': final_r2
}

=== Результаты Optuna на схеме GroupKFold ===
Лучшие параметры: {'alpha': 0.0017337747993137799, 'l1_ratio': 0.11664026132206926}
Метрики на валидации -> MAE: 704.33119 | RMSE: 999.06908 | R2: 0.57043

### Сводная таблица сравнения подходов

In [22]:
res_optuna = {
    'model': 'Optuna Baseline',
    'alpha': best_params['alpha'],
    'l1_ratio': best_params['l1_ratio'],
    'MAE': mae_opt,
    'RMSE': rmse_opt,
    'R2': r2_opt
}


res_grid_fixed = {**res_grid, 'model': 'Grid Search'}
res_random_fixed = {**res_random, 'model': 'Random Search'}
res_group_cv_fixed = {**res_group_cv, 'model': 'Optuna + GroupKFold'}


summary_opt_df = pd.DataFrame([
    res_grid_fixed, 
    res_random_fixed, 
    res_optuna,          
    res_group_cv_fixed
])


columns_order = ['model', 'alpha', 'l1_ratio', 'MAE', 'RMSE', 'R2']
summary_opt_df = summary_opt_df[columns_order]

print("=== СВОДНАЯ ТАБЛИЦА СРАВНЕНИЯ МЕТОДОВ ОПТИМИЗАЦИИ ГИПЕРПАРАМЕТРОВ ===")
summary_opt_df

=== СВОДНАЯ ТАБЛИЦА СРАВНЕНИЯ МЕТОДОВ ОПТИМИЗАЦИИ ГИПЕРПАРАМЕТРОВ ===

                 model   alpha  l1_ratio       MAE      RMSE      R2
0          Grid Search 0.01000   0.90000 704.35862 999.04614 0.57045
1        Random Search 0.01285   0.65000 704.23078 999.28274 0.57025
2      Optuna Baseline 0.00135   0.52031 704.38234 999.03304 0.57046
3  Optuna + GroupKFold 0.00173   0.11664 704.33119 999.06908 0.57043

###  Анализ результатов и сравнение подходов оптимизации

1. **Grid Search (Перебор по сетке):** 
   Метод выполнил полный детерминированный перебор параметров по заданной фиксированной матрице координат. Он находит лучший результат только в том случае, если шаг сетки изначально был выбран очень мелким. Метод не учитывает взаимосвязи между параметрами и тратит ресурсы на проверку неэффективных комбинаций.

2. **Random Search (Случайный поиск):**
   Благодаря хаотичному выбору непрерывных значений из диапазона `np.linspace`, метод за те же 15 итераций проверил 15 уникальных вариантов `alpha` и `l1_ratio`, не дублируя вычисления. На практике случайный поиск часто находит более точные комбинации параметров, чем крупная фиксированная сетка.

3. **Optuna (Байесовская оптимизация на алгоритме TPE):**
   Является наиболее эффективным и «умным» подходом. Алгоритм разделяет историю запусков на условные группы «хороших» и «плохих» параметров. Каждая следующая итерация выбирается так, чтобы максимизировать вероятность попадания в зону высокой метрики качества $R^2$. Это позволяет находить оптимальные гиперпараметры за значительно меньшее число шагов.

4. **Интеграция со схемами перекрестной проверки (Optuna + GroupKFold):**
   Запуск `Optuna` в связке с кастомным `GroupKFold` по полю `manager_id` является наиболее надежным решением с точки зрения бизнес-логики. Данный подход гарантирует, что модель ElasticNet подбирает внутренние веса штрафов регуляризации не под конкретный стиль риелторов, а под общие рыночные свойства квартир (количество комнат, удобств). Полученные таким образом гиперпараметры обладают максимальной обобщающей способностью и защищены от переобучения.

In [23]:
%%time
grid_search.fit(X_train, y_train)

CPU times: user 2.34 s, sys: 1.58 s, total: 3.93 s
Wall time: 3.28 s

GridSearchCV(cv=3, estimator=ElasticNet(max_iter=5000, random_state=42),
             n_jobs=-1,
             param_grid={'alpha': [0.01, 0.1, 0.5, 1.0, 5.0],
                         'l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9]},
             scoring='r2')

In [24]:
%%time
study_group_cv.optimize(objective_group_cv, n_trials=15)

CPU times: user 21.4 s, sys: 9.81 ms, total: 21.4 s
Wall time: 1.9 s